version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "greeter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8i89wmihkj5n"
s3_prefix = "greeter"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
